# -----------------------------------
# -------- OPENOCD SERVER -----------
# -----------------------------------
FROM ubuntu:16.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    openocd

# Expose port
EXPOSE 4444
# on archlinux
#CMD openocd -s /usr/share/openocd/scripts
# on macOS
#CMD openocd -s /usr/local/Cellar/open-ocd/0.8.0/share/openocd/scripts/ \
    -f interface/stlink.cfg \
    -f target/nrf51.tcl
CMD tail -f /dev/null
